### ISSUE TITLE
Cannot edit, Customer.json not found

### ISSUE THREAD

**Issue by ksystemsio** [User1m/blockchain-dapp-hack-starter#1]
Hello! Great job, but I cannot get the edit function to work, when I load the test page, in the console I see "18.03.01 12:34:33 404 GET /Customer.json". If I click on the edit botton, nothing happens, and if I run edit.html manually, I cannot submit any change. I tried it on my testnet on both ports 8545 and 9545, but I think I am missing some parameters in order to properly initialize geth. Thanks for your great work!!!

Also running testrpc, things won't change, it looks like truffle is only compiling the migrations contract

**Comment by user1m** [comment]
hi @ksystemsio here's where [Customer.json](https://github.com/User1m/blockchain-dapp-hack-starter/blob/master/src/customers.json) is found. I'm not able to debug your problem w/o more visibility into your code but hopefully this helps.
